#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

export GOARCH=${1:-$(uname -m)}
if [ $GOARCH == x86_64 ]; then
    export GOARCH=amd64
fi

mkdir -p bin
[ "$(uname)" != "Darwin" ] && LINKFLAGS="-extldflags -static -s"
CGO_ENABLED=0 go build -ldflags "-X main.VERSION=$VERSION $LINKFLAGS -extldflags -static -s" -o bin/share-mnt
